name: legacy_lane_fresh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  google_sign_in: ^6.2.1
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.8
  logger: ^2.6.1
  flutter_image_compress: ^2.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
