// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdmcaAVkRaqCZ_TGuWL6bvt0Lr9LV1xhI',
    appId: '1:598745726375:web:2aa5bd2cb50f84c3154a82',
    messagingSenderId: '598745726375',
    projectId: 'legacy-lane-ds-fb',
    authDomain: 'legacy-lane-ds-fb.firebaseapp.com',
    storageBucket: 'legacy-lane-ds-fb.firebasestorage.app',
    measurementId: 'G-VLXDRK590C',
  );

// ... existing code ...

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfp_YrD2zxlEcCGuyqthSAH0rCPFDuGX4',
    appId: '1:598745726375:android:1850de445d9fcd8a154a82',
    messagingSenderId: '598745726375',
    projectId: 'legacy-lane-ds-fb',
    storageBucket: 'legacy-lane-ds-fb.firebasestorage.app',
  );

static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'your-ios-api-key',
  appId: 'your-ios-app-id',
  messagingSenderId: '123456789',
  projectId: 'your-project-id',
  storageBucket: 'your-project-id.appspot.com',
);
}